version: '3'

set: [pipefail]

tasks:
  default:
    cmds:
      - task --list

  dev-setup:
    desc: Bootstrap dev setup
    cmds:
      - uv tool install prek
      - prek install

  maintenance:
    desc: Project maintenance automation
    cmds:
      - prek auto-update
