---
extends: default

rules:
  document-start:
    ignore: |
      .pre-commit-config.yaml
      copier.yml
      Taskfile.yaml
  new-line-at-end-of-file: disable
  new-lines:
    type: unix
  line-length:
    max: 120
