[tool.ruff]
line-length = 88
target-version = "py313"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D203",
    "D213",
    "Q000",
    "Q003",
    "COM812",
]

[tool.ruff.lint.isort]
known-first-party = ["helpers"]

[tool.ruff.lint.extend-per-file-ignores]
# https://github.com/astral-sh/ruff/issues/4368#issuecomment-2245567481
"tests/**/*.py" = [
    # at least this three should be fine in tests:
    "S101", # asserts allowed in tests...
    "ARG", # Unused function args -> fixtures nevertheless are functionally relevant...
    "FBT", # Don't care about booleans as positional arguments in tests, e.g. via @pytest.mark.parametrize()
    # The below are debateable
    "PLR2004", # Magic value used in comparison, ...
    "S311", # Standard pseudo-random generators are not suitable for cryptographic purposes
    "INP001", # https://github.com/astral-sh/ruff/issues/6474
    "D103", # Tests can self document
]
"extensions/*.py" = [
    "INP001",
    "ANN401",
]

[tool.ruff.format]
quote-style = "single"

[tool.pip-tools]
generate-hashes = true
strip-extras = true
