version: '3'

set: [pipefail]

includes:
  dev-setup: ./taskfile/copier-template/dev-setup
  test: ./taskfile/copier-template/test
  diff: ./taskfile/copier-template/diff
  example: ./taskfile/copier-template/example
  release: ./taskfile/copier-template/release

tasks:
  default:
    cmds:
      - task --list
