version: '3'

tasks:
  default:
    desc: Bootstrap dev setup
    cmds:
      - task: venv
      - uv run prek install

  venv:
    desc: Install dev requirements
    cmds:
      - uv sync

  maintenance:
    desc: Project maintenance automation
    cmds:
      - uv run prek auto-update
      - task: maintenance:requirements

  maintenance:requirements:
    vars:
      CLI_ARGS: '{{.CLI_ARGS | default "--upgrade" }}'
    cmds:
      - task: venv
      - uv lock {{.CLI_ARGS}}
